export default class ANNOTATIONTYPES {
    public static readonly ANNOTATIONTYPE_USEPAIR = "ANNOTATIONTYPE_USEPAIR";
    public static readonly ANNOTATIONTYPE_USERANK = "ANNOTATIONTYPE_USERANK";
    public static readonly ANNOTATIONTYPE_WSSIM = "ANNOTATIONTYPE_WSSIM";
    public static readonly ANNOTATIONTYPE_LEXSUB = "ANNOTATIONTYPE_LEXSUB";
}